apiVersion: v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-h
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        volumeMounts: 
        - mountPath: /var/lib/mysql
          name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
  volumeClaimTemplates:
    - metadata:
      name: data-volume
      spec:
        accessModes:
        - ReadWriteOnce
          storageClassName: google-storage
            resources:
              requests:

