repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: \.(go|yml|yaml)$
      - id: end-of-file-fixer
        files: \.(go|yml|yaml)$
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: check-added-large-files  # Impede commits de arquivos muito grandes
      - id: detect-private-key  # Evita o commit acidental de chaves privadas

  - repo: local
    hooks:
      - id: golangci-lint
        name: GolangCI-Lint
        entry: golangci-lint
        args: ["run", "--config", ".golangci.yml", "./app/..."]
        language: system
        types: [go]
        pass_filenames: false

      - id: go-fmt
        name: Go fmt
        entry: go
        args: ["fmt", "./app/..."]
        language: system
        types: [go]
        pass_filenames: false

      - id: go-vet
        name: Go vet
        entry: go
        args: ["vet", "./app/..."]
        language: system
        types: [go]
        pass_filenames: false
      
      - id: gosec
        name: Gosec Security Check
        entry: gosec
        args: ["./app/..."]
        language: system
        types: [go]
        pass_filenames: false

      - id: go-test
        name: Go Test
        entry: go
        args: ["test", "-short", "./app/..."]
        language: system
        types: [go]
        pass_filenames: false

      - id: go-mod-tidy  # Garante que o `go.mod` e `go.sum` estejam limpos
        name: Go Mod Tidy
        entry: go
        args: ["mod", "tidy"]
        language: system
        types: [go]
        pass_filenames: false

      - id: check-json  # Verifica a sintaxe de arquivos JSON
        name: Check JSON
        entry: jq .
        language: system
        types: [json]

      - id: check-merge-conflict  # Verifica se existem conflitos não resolvidos
        name: Check Merge Conflict
        entry: grep -E '^(<<<<<<<|=======|>>>>>>>|\|\|\|\|\|\|)$'
        language: system
        files: .*
        exclude: ^(.git/|node_modules/)
        pass_filenames: false