kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31000 #vote
        hostPort: 8080
        protocol: TCP

      - containerPort: 31001 #result
        hostPort: 8081
        protocol: TCP